### PR TITLE
[WIP] Fixes #3894 - Only Use Highest Foci Bonus For Spells

### LINKED ISSUE #3894: Power and combat spellcasting focus both adding to dice pools in 5e
**Describe the bug**
Both Power focus and combat spellcasting focus are adding to combat dice pools

**To Reproduce**
1. Go to Gear
2. Click on Add Gear
     Add power focus rank 1
     Add Spellcasting focus, combat rank 2
     Bind both foci
3. Go to Skills, Spellcasting, see Power focus added to dice pool
4. Go to Spells and Spirits, any combat spell, see Spellcasting Focus, combat added to dice pool

**Expected behavior**
Only the highest force focus should add to the dice pool

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version 5.208.0

chummer_spellcasting
chummer_manabolt

### PR DESCRIPTION
**Pull request by MemeticContagion**
Hi! I saw this was open and thought I would take a stab at fixing it. This is the first time I've done anything with .NET, so please let me know if this is the wildly wrong approach. I'll try to comment the PR where I have questions or I think I'm doing anything especially strange. 

This checks on calculating the spell dice poll to see if the character has other bonded foci, and if so, if any of them are power foci that are added to the base MAG score. If there are any power foci with a value higher than the specialized focus, it just skips adding in the specialized focuses value. 

If there is a power focus but the highest value one is below the rating of the specialized focus, it gives a bonus for the specialized focus that is the diff of the power focus - specialized focus. My current approach to doing that is almost certainly non-standard.

### CODE REVIEW

File: Chummer/Backend/Uniques/Spell.cs [hunk 1]
```diff
@@ -859,6 +874,42 @@ private IEnumerable<Improvement> RelevantImprovements(Func<Improvement, bool> fu
...
+                _objCharacter.Foci.Where(x => x.GearObject.Bonus.InnerText == "MAGRating" && x.GearObject.Bonded);
+            int powerFocusRating = fociList.Any()
+                ? fociList.OrderByDescending(x => x.Rating)?.FirstOrDefault().Rating ?? default(int)
+                : default(int);
+            // If our focus is higher, add in a partial bonus
+            if (powerFocusRating > 0 && powerFocusRating < objImprovement.Value)
+            {
+                // This is hackz -- because we don't want to lose the original improvement's value
+                // we instantiate a fake version of the improvement that isn't saved to represent the diff
+                return new Improvement(_objCharacter)
```
Comment (MemeticContagion) [inline Chummer/Backend/Uniques/Spell.cs]: This is the weirdest part of this PR, I think--we're basically creating a fake improvement representing the diff. But we don't want to modify the real improvement's value, since if the power focus is ever unbonded, we'll end up wanting to put the full value improvement back into play. Open to suggestions!

File: Chummer/Backend/Uniques/Spell.cs [hunk 2]
```diff
@@ -849,6 +849,21 @@ private IEnumerable<Improvement> RelevantImprovements(Func<Improvement, bool> fu
                             yield return objImprovement;
                         break;
                     case Improvement.ImprovementType.SpellCategory:
+                        // We need to do some checking to make sure this is the most powerful foci before we add it in
+                        if (objImprovement.ImproveSource == Improvement.ImprovementSource.Gear )
```
Comment (MemeticContagion) [inline Chummer/Backend/Uniques/Spell.cs]: Is this the best way to see if the SpellCategory improvement is a focus? Is there a narrower category I should be using?

File: Chummer/Backend/Uniques/Spell.cs [hunk 3]
```diff
@@ -859,6 +875,42 @@ private IEnumerable<Improvement> RelevantImprovements(Func<Improvement, bool> fu
...
         }
+
+        /// <summary>
+        /// Method to check we are only applying the highest focus to the spell dicepool
+        /// </summary>
+        private Improvement CompareFocusPower(Improvement objImprovement)
+        {
+            // get any bonded foci that add to the base magic stat and return the highest rated one's rating
+            IEnumerable<Focus> fociList =
+                _objCharacter.Foci.Where(x => x.GearObject.Bonus.InnerText == "MAGRating" && x.GearObject.Bonded);
```
Comment (MemeticContagion) [inline Chummer/Backend/Uniques/Spell.cs]: Is this the best way to find any foci that add directly to the magic rating?

File: Chummer/Backend/Uniques/Spell.cs (hunk 2 above)
Comment (chummer5a) [reply Chummer/Backend/Uniques/Spell.cs]: Yeah, there's not really anything cuter than that. You could ghetto something with GetSourceName, but it'd be a kludge.

**Comment by chummer5a** [comment]
I'd have preferred to have seen something data-driven, but this is actually fairly elegant 👍
